### ISSUE TITLE
DMQ Joins

### ISSUE THREAD

**Issue by kevharvell** [kevharvell/StockLikes#6]
Work on DMQ file join for gaming company search. Should join Twitter, stock, and games.

**Comment by willdarnell** [comment]
is this redundant or a separate thing?

**Comment by kevharvell** [comment]
hrm? I think you did this. Basically the INNER JOIN on our home page that shows all the data on each gaming company.

**Comment by kevharvell** [comment]
nvm, see what you mean... sorry
